### PR TITLE
remove absolute url in type

### PR DESCRIPTION
**Pull request by oliveregger**
see discussion in [zulip:CDA Logical elements, when to use absolute url?](https://chat.fhir.org/#narrow/stream/198221-cda.2Fpublish/topic/CDA.20Logical.20elements.2C.20when.20to.20use.20absolute.20url.3F)

### CODE REVIEW

**Comment by seanmcilvenna** [comment]
Is this a partial commit for the whole fix? I have a hard time believing we long reference those URLs in these 15 files...

**Comment by grahamegrieve** [comment]
Looks like everything to me - just where StructureDefinition.type has a URL, it shouldn’t

**Comment by seanmcilvenna** [comment]
What about AuthoringDevice?
```
    <element id="AuthoringDevice.code">
      <path value="AuthoringDevice.code"/>
      <min value="0"/>
      <max value="1"/>
      <type>
        <code value="http://hl7.org/fhir/cda/StructureDefinition/CE"/>
      </type>
      <binding>
        <strength value="extensible"/>
        <valueSetUri value="http://hl7.org/fhir/ValueSet/v3-EntityCode"/>
      </binding>
    </element>
```

**Comment by oliveregger** [comment]
It is only StructureDefinition.type where the absolute Url has been removed for this pull request, eg. in AuthoringDevice StructureDefinition.type:   <type value="AuthoringDevice"/>.

The type.code value element you refer in the ElementDefinitions is currently everywhere in the CDA logical model defined as an absolute uri.  If there the absolute url would be removed I think at least a profile would need to be added that the type can be resolved to which logical model type it belongs.

**Comment by oliveregger** [comment]
and the spec says for [ElementDefinition.type.code](http://hl7.org/fhir/elementdefinition-definitions.html):

> Definition | URL of Data type or Resource that is a(or the) type used for this element. References are URLs that are relative to http://hl7.org/fhir/StructureDefinition e.g. "string" is a reference to http://hl7.org/fhir/StructureDefinition/string. Absolute URLs are only allowed in logical models.

so it can't be without an absolute url for the logical model because a relative reference would not be correct.

**Pull request merged**
