### PR TITLE
Re-add sdtc:admissionReferralSourceCode

### PR DESCRIPTION
**Pull request by mjszczep**
(Talked about this at the WGM but here's a pull request... this should be all we need.)

### CODE REVIEW

**Comment by minigrrl** [comment]
Hey Matt - I've actually got all the changes for this ready to go. I was waiting on write access to the repo (which I think I have now, I just haven't tried pushing again). Looks like you have made the changes also? I'm fine with your stuff being added - just making sure we are on the same page...

**Comment by mjszczep** [comment]
Ahh, my bad! Hopefully our changes should be identical though (since there's not much room to get creative with this) so you can totally feel free to do whatever's easier whether it's using your changes or my PR.

I just came back to this today and figured I'd make the PR so we didn't forget about it; didn't realize that you were still on top of it!

**Comment by minigrrl** [comment]
"on top of it" is generous. I'd totally forgotten I was waiting. I'll try a push now and see what happens!

**Comment by minigrrl** [comment]
@mjszczep - I've committed the changes now. Maybe you could double check them to make sure they are what you are expecting?

**Comment by mjszczep** [comment]
Is the datatype supposed to be CD or CE? Other than that it looks good (although I'm a little curious about why you rearranged the stuff in SDTC.xsd).

**Comment by grahamegrieve** [comment]
Can we close this now?

**Comment by mjszczep** [comment]
So I just blew off the dust on this PR and it still seems like the data type should be CE rather than CD (at least, [it's CE in CDA 2.1](https://github.com/HL7/CDA-core-2.1/blob/master/schemas/normative/POCD_MT000040UV02.xsd#L474)). I still think we should resolve that before closing this...

**Comment by mjszczep** [comment]
So I once again remembered that this is (IMO) an outstanding issue; I still think the data type should technically be `CE`, not `CD`. @minigrrl, how do you feel about merging this in on top of your original fix?

**Comment by benjaminflessner** [comment]
Closing after discussion in Skype - @minigrrl and @mjszczep agreed with type=CE to match CDA 2.1 and the current CDA-SD format. That change has been applied in https://github.com/HL7/CDA-core-2.0/commit/260617b63e421dbd5218645f678fdaf2fe1e844b

**Pull request closed without merging**
